(function() {var implementors = {};
implementors["trillium_basic_auth"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_basic_auth/struct.BasicAuth.html\" title=\"struct trillium_basic_auth::BasicAuth\">BasicAuth</a>","synthetic":false,"types":["trillium_basic_auth::BasicAuth"]}];
implementors["trillium_cookies"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_cookies/struct.Cookies.html\" title=\"struct trillium_cookies::Cookies\">Cookies</a>","synthetic":false,"types":["trillium_cookies::Cookies"]}];
implementors["trillium_handlebars"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_handlebars/struct.Handlebars.html\" title=\"struct trillium_handlebars::Handlebars\">Handlebars</a>","synthetic":false,"types":["trillium_handlebars::Handlebars"]}];
implementors["trillium_html_rewriter"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_html_rewriter/struct.HtmlRewriter.html\" title=\"struct trillium_html_rewriter::HtmlRewriter\">HtmlRewriter</a>","synthetic":false,"types":["trillium_html_rewriter::HtmlRewriter"]}];
implementors["trillium_logger"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_logger/struct.DevLogger.html\" title=\"struct trillium_logger::DevLogger\">DevLogger</a>","synthetic":false,"types":["trillium_logger::DevLogger"]}];
implementors["trillium_proxy"] = [{"text":"impl&lt;Transport:&nbsp;<a class=\"trait\" href=\"trillium_proxy/trait.ClientTransport.html\" title=\"trait trillium_proxy::ClientTransport\">ClientTransport</a>&gt; <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_proxy/struct.Proxy.html\" title=\"struct trillium_proxy::Proxy\">Proxy</a>&lt;Transport&gt;","synthetic":false,"types":["trillium_proxy::Proxy"]}];
implementors["trillium_router"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_router/struct.Router.html\" title=\"struct trillium_router::Router\">Router</a>","synthetic":false,"types":["trillium_router::Router"]}];
implementors["trillium_sessions"] = [{"text":"impl&lt;Store:&nbsp;<a class=\"trait\" href=\"async_session/session_store/trait.SessionStore.html\" title=\"trait async_session::session_store::SessionStore\">SessionStore</a>&gt; <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_sessions/struct.Sessions.html\" title=\"struct trillium_sessions::Sessions\">Sessions</a>&lt;Store&gt;","synthetic":false,"types":["trillium_sessions::Sessions"]}];
implementors["trillium_static"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_static/struct.Static.html\" title=\"struct trillium_static::Static\">Static</a>","synthetic":false,"types":["trillium_static::Static"]}];
implementors["trillium_static_compiled"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_static_compiled/struct.StaticCompiled.html\" title=\"struct trillium_static_compiled::StaticCompiled\">StaticCompiled</a>","synthetic":false,"types":["trillium_static_compiled::StaticCompiled"]}];
implementors["trillium_tera"] = [{"text":"impl <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_tera/struct.TeraHandler.html\" title=\"struct trillium_tera::TeraHandler\">TeraHandler</a>","synthetic":false,"types":["trillium_tera::TeraHandler"]}];
implementors["trillium_websockets"] = [{"text":"impl&lt;H, Fut&gt; <a class=\"trait\" href=\"trillium/handler/trait.Handler.html\" title=\"trait trillium::handler::Handler\">Handler</a> for <a class=\"struct\" href=\"trillium_websockets/struct.WebSocket.html\" title=\"struct trillium_websockets::WebSocket\">WebSocket</a>&lt;H&gt; <span class=\"where fmt-newline\">where<br>&nbsp;&nbsp;&nbsp;&nbsp;H: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/ops/function/trait.Fn.html\" title=\"trait core::ops::function::Fn\">Fn</a>(<a class=\"struct\" href=\"trillium_websockets/struct.WebSocketConnection.html\" title=\"struct trillium_websockets::WebSocketConnection\">WebSocketConnection</a>) -&gt; Fut + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + 'static,<br>&nbsp;&nbsp;&nbsp;&nbsp;Fut: <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/future/future/trait.Future.html\" title=\"trait core::future::future::Future\">Future</a>&lt;Output = <a class=\"primitive\" href=\"https://doc.rust-lang.org/nightly/std/primitive.unit.html\">()</a>&gt; + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Send.html\" title=\"trait core::marker::Send\">Send</a> + <a class=\"trait\" href=\"https://doc.rust-lang.org/nightly/core/marker/trait.Sync.html\" title=\"trait core::marker::Sync\">Sync</a> + 'static,&nbsp;</span>","synthetic":false,"types":["trillium_websockets::WebSocket"]}];
if (window.register_implementors) {window.register_implementors(implementors);} else {window.pending_implementors = implementors;}})()